# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PopTheCob' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PopTheCob
  pod 'Firebase/Firestore'
  pod 'Firebase/Analytics'

  target 'PopTheCobTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PopTheCobUITests' do
    # Pods for testing
  end

end
